<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.team33.patterns</groupId>
        <artifactId>patterns-lib</artifactId>
        <version>2.10.1</version>
    </parent>

    <artifactId>io-thalassa</artifactId>

    <name>Team33 IO Library Aggregate - Edition "thalassa"</name>
    <description>Backward compatibility module providing the former io-thalassa dependency
        as an aggregate of io-thalassa-base and io-thalassa-records.
    </description>

    <dependencies>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>io-thalassa-base</artifactId>
        </dependency>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>io-thalassa-records</artifactId>
        </dependency>
    </dependencies>
</project>
