<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.team33.patterns</groupId>
        <artifactId>patterns-lib</artifactId>
        <version>2.10.0-SNAPSHOT</version>
    </parent>

    <artifactId>zz-records-metis</artifactId>

    <name>DRAFT: Team33 Records Library - Edition "metis"</name>
    <description>Provides conversions between Records and Map representations.</description>

    <properties>
        <skipJavadoc>true</skipJavadoc>
        <skipHome>true</skipHome>
        <skipGPG>true</skipGPG>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>lazy-janus</artifactId>
        </dependency>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>zz-typing-proteus</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>zz-streamable-naiad</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>zz-collection-mneme</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>de.team33.patterns</groupId>
            <artifactId>arbitrary-mimas</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
